spring:
          profiles:
                  active: development

---

spring:
          profiles: development

server:
          port: 8083

db:
          driver: "com.mysql.jdbc.Driver"
          url: "jdbc:mysql://localhost:3306/bbcvdb"
          usr: "root"
          password: "root"

hibernate:
          dialect: "org.hibernate.dialect.MySQLInnoDBDialect"
          show_sql: "true"
          connection:
                    characterEncoding: "UTF-8"

---

spring:
          profiles: localtest

server:
          port: 8084

db:
          driver: "com.mysql.jdbc.Driver"
          url: "jdbc:mysql://localhost:3306/bbcvdblocaltest"
          usr: "root"
          password: "root"

hibernate:
          dialect: "org.hibernate.dialect.MySQLInnoDBDialect"
          show_sql: "true"
          connection:
                    characterEncoding: "UTF-8"

---

spring:
          profiles: production

server:
          port: 8084
