spring:
        profiles:
                  active: development

---

spring:
          profiles: development

server:
          port: 8081

ro:
  leje:
    services:
      user: "http://localhost:8083/api/user"
      role: "http://localhost:8083/api/role"

---

spring:
          profiles: localtest

server:
          port: 8085

ro:
  leje:
    services:
      user: "http://localhost:8084/api/user"
      role: "http://localhost:8084/api/role"
---

spring:
          profiles: production

server:
          port: 8082

ro:
  leje:
    services:
      user: "http://localhost:8083/api/user"
      role: "http://localhost:8083/api/role"