spring:
        profiles:
                  active: development

---

logging:
          file: /var/log/bbcv/webapp.log

spring:
          profiles: development

server:
          port: 8081

ro:
  leje:
    services:
      user: "http://localhost:8083/api/user"
      role: "http://localhost:8083/api/role"
      link: "http://localhost:8083/api/link"

---

spring:
          profiles: localtest

server:
          port: 8085

ro:
  leje:
    services:
      user: "http://localhost:8084/api/user"
      role: "http://localhost:8084/api/role"
      link: "http://localhost:8084/api/link"
---

spring:
          profiles: production

server:
          port: 8082

ro:
  leje:
    services:
      user: "http://localhost:8083/api/user"
      role: "http://localhost:8083/api/role"
      link: "http://localhost:8083/api/link"