spring:
        profiles:
                  active: development

---

logging:
          file: /var/log/bbcv/webapp.log

spring:
          profiles: development

server:
          port: 8081

ro:
  leje:
    services:
      users: "http://localhost:8083/api/v1/users"
      roles: "http://localhost:8083/api/v1/roles"
      links: "http://localhost:8083/api/v1/links"

---

spring:
          profiles: localtest

server:
          port: 8085

ro:
  leje:
    services:
      users: "http://localhost:8084/api/v1/users"
      roles: "http://localhost:8084/api/v1/roles"
      links: "http://localhost:8084/api/v1/links"
---

spring:
          profiles: production

server:
          port: 8082

ro:
  leje:
    services:
      users: "http://localhost:8083/api/v1/users"
      roles: "http://localhost:8083/api/v1/roles"
      links: "http://localhost:8083/api/v1/links"