spring:
        profiles:
                  active: development

---

logging:
          file: /var/log/bbcv/webapp.log

spring:
          profiles: development

server:
          port: 8081

db:
          driver: "com.mysql.jdbc.Driver"
          url: "jdbc:mysql://localhost:3307/bbcvdb"
          usr: "testuser"
          password: "testpassword"

hibernate:
          dialect: "org.hibernate.dialect.MySQLInnoDBDialect"
          show_sql: "true"
          connection:
                    characterEncoding: "UTF-8"

articles:
          images: "/Users/danut/Projects/resources/bbcv/articles/images/"

---

spring:
          profiles: test

server:
          port: 8085

db:
          driver: "com.mysql.jdbc.Driver"
          url: "jdbc:mysql://localhost:3307/bbcvdbtest"
          usr: "testuser"
          password: "testpassword"

hibernate:
          dialect: "org.hibernate.dialect.MySQLInnoDBDialect"
          show_sql: "true"
          connection:
                    characterEncoding: "UTF-8"

articles:
          images: "/path/to/articles/images/"

---

spring:
          profiles: production

server:
          port: 8082

db:
          driver: "com.mysql.jdbc.Driver"
          url: "jdbc:mysql://localhost:3307/bbcvdblocaltest"
          usr: "testuser"
          password: "testpassword"

hibernate:
          dialect: "org.hibernate.dialect.MySQLInnoDBDialect"
          show_sql: "true"
          connection:
                    characterEncoding: "UTF-8"

articles:
          images: "/path/to/articles/images/"
